id: ICB84F79D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-20T11:34:19+00:00'
last_modified: '2022-06-09T17:40:56.903766+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10287
  title: རྒྱ་གཟའ་བལ་བཟའི་རྣམ་ཐར། ༼དབུ་ཅན་བྲིས་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BE24:
      image_group_id: I1KG10341
      title: Volume 1 of rgya gza' bal bza'i rnam thar/ (dbu chen bris ma/)
      total_pages: 276
      order: 1
      base_file: BE24.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
